//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Reset.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client_Reset.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1200px_Microsoft_Store_app_icon {
            get {
                object obj = ResourceManager.GetObject("1200px-Microsoft_Store_app_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1200px_Microsoft_Store_app_icon1 {
            get {
                object obj = ResourceManager.GetObject("1200px-Microsoft_Store_app_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688431_api_config_configuration_machine_wrench_icon {
            get {
                object obj = ResourceManager.GetObject("3688431_api_config_configuration_machine_wrench_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688440_delete_remove_trash_bin_dustbin_icon {
            get {
                object obj = ResourceManager.GetObject("_3688440_delete_remove_trash_bin_dustbin_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688454_find_lens_search_magnifier_magnifying_icon {
            get {
                object obj = ResourceManager.GetObject("3688454_find_lens_search_magnifier_magnifying_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688457_refresh_sync_map_reload_rotate_icon {
            get {
                object obj = ResourceManager.GetObject("3688457_refresh_sync_map_reload_rotate_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688503_close_cross_delete_remove_bin_icon {
            get {
                object obj = ResourceManager.GetObject("3688503_close_cross_delete_remove_bin_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688505_check_done_right_accept_ok_icon {
            get {
                object obj = ResourceManager.GetObject("3688505_check_done_right_accept_ok_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688521_arrows_direction_download_pointer_up_icon {
            get {
                object obj = ResourceManager.GetObject("3688521_arrows_direction_download_pointer_up_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688523_arrow_left_arrows_direction_down_icon {
            get {
                object obj = ResourceManager.GetObject("3688523_arrow_left_arrows_direction_down_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688524_arrow_bottom_arrows_direction_down_icon {
            get {
                object obj = ResourceManager.GetObject("3688524_arrow_bottom_arrows_direction_down_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688524_arrow_bottom_arrows_direction_down_icon1 {
            get {
                object obj = ResourceManager.GetObject("3688524_arrow_bottom_arrows_direction_down_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688525_align_angle_chevron_top_html_tag_icon {
            get {
                object obj = ResourceManager.GetObject("3688525_align_angle_chevron_top_html tag_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688526_angle_left_chevron_icon {
            get {
                object obj = ResourceManager.GetObject("3688526_angle_left_chevron_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3688527_down_chevron_angle_bottom_align_icon {
            get {
                object obj = ResourceManager.GetObject("3688527_down_chevron_angle_bottom_align_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4572454_middle {
            get {
                object obj = ResourceManager.GetObject("4572454-middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4572454_middle1 {
            get {
                object obj = ResourceManager.GetObject("4572454-middle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B2F3_Uplay_0_2 {
            get {
                object obj = ResourceManager.GetObject("B2F3_Uplay.0.2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barline_Loading_Images_1 {
            get {
                object obj = ResourceManager.GetObject("Barline-Loading-Images-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Battlenet_2021_icon {
            get {
                object obj = ResourceManager.GetObject("Battlenet_2021_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Battlenet_2021_icon1 {
            get {
                object obj = ResourceManager.GetObject("Battlenet_2021_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Capture {
            get {
                object obj = ResourceManager.GetObject("Capture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Epic_Games_Node_xlarge_whitetext_blackback_epiclogo_504x512_1529964470588_503x512_ac795e81c54b27aaa2e196456dd307bfe4ca3ca4 {
            get {
                object obj = ResourceManager.GetObject("Epic+Games+Node_xlarge_whitetext_blackback_epiclogo_504x512_1529964470588-503x512" +
                        "-ac795e81c54b27aaa2e196456dd307bfe4ca3ca4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Epic_Games_Node_xlarge_whitetext_blackback_epiclogo_504x512_1529964470588_503x512_ac795e81c54b27aaa2e196456dd307bfe4ca3ca41 {
            get {
                object obj = ResourceManager.GetObject("Epic+Games+Node_xlarge_whitetext_blackback_epiclogo_504x512_1529964470588-503x512" +
                        "-ac795e81c54b27aaa2e196456dd307bfe4ca3ca41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gog_galaxy {
            get {
                object obj = ResourceManager.GetObject("gog-galaxy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gog_galaxy1 {
            get {
                object obj = ResourceManager.GetObject("gog-galaxy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Origin_logo {
            get {
                object obj = ResourceManager.GetObject("Origin-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Origin_logo1 {
            get {
                object obj = ResourceManager.GetObject("Origin-logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_world_of_warcraft_battle_net_hearthstone_blizzard_entertainment_call_of_duty_black_ops_4_world_of_warcraft_game_logo {
            get {
                object obj = ResourceManager.GetObject("png-clipart-world-of-warcraft-battle-net-hearthstone-blizzard-entertainment-call-" +
                        "of-duty-black-ops-4-world-of-warcraft-game-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_world_of_warcraft_battle_net_hearthstone_blizzard_entertainment_call_of_duty_black_ops_4_world_of_warcraft_game_logo1 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-world-of-warcraft-battle-net-hearthstone-blizzard-entertainment-call-" +
                        "of-duty-black-ops-4-world-of-warcraft-game-logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_blue_logo_battle_net_computer_icons_blizzard_entertainment_video_game_world_of_warcraft_jainism_game_leaf_text {
            get {
                object obj = ResourceManager.GetObject("png-transparent-blue-logo-battle-net-computer-icons-blizzard-entertainment-video-" +
                        "game-world-of-warcraft-jainism-game-leaf-text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_blue_logo_battle_net_computer_icons_blizzard_entertainment_video_game_world_of_warcraft_jainism_game_leaf_text1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-blue-logo-battle-net-computer-icons-blizzard-entertainment-video-" +
                        "game-world-of-warcraft-jainism-game-leaf-text1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_diablo_iii_battle_net_destiny_2_world_of_warcraft_battlefield_blue_logo_teal {
            get {
                object obj = ResourceManager.GetObject("png-transparent-diablo-iii-battle-net-destiny-2-world-of-warcraft-battlefield-blu" +
                        "e-logo-teal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_diablo_iii_battle_net_destiny_2_world_of_warcraft_battlefield_blue_logo_teal1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-diablo-iii-battle-net-destiny-2-world-of-warcraft-battlefield-blu" +
                        "e-logo-teal1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Steam_icon_logo_svg {
            get {
                object obj = ResourceManager.GetObject("Steam_icon_logo.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Steam_icon_logo1 {
            get {
                object obj = ResourceManager.GetObject("Steam_icon_logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unnamed {
            get {
                object obj = ResourceManager.GetObject("unnamed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unnamed1 {
            get {
                object obj = ResourceManager.GetObject("unnamed1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Uplay_Logo {
            get {
                object obj = ResourceManager.GetObject("Uplay_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Uplay_Logo1 {
            get {
                object obj = ResourceManager.GetObject("Uplay_Logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
